### ISSUE TITLE
Add dependency to Azure Artifacts-keyring package

### ISSUE THREAD

**Issue by gbmarc1** [conda-forge/staged-recipes#10326]
Add "Artifacts-keyring" package to conda-forge:

https://pypi.org/project/artifacts-keyring/

It is not possible to use a env.yaml file to install and package that is located on an AzurePypi.

This does not work because `artifacts-keyring` needs to be installed first BEFORE resolving the packages using pip.

```yaml
name: my_name
channels:
  - conda-forge
dependencies:
  - python=3.7
  - keyring
  - pip:
      - artifacts-keyring
      - AzurePypi_package
```

This would work because `artifacts-keyring` would be installed first.

```yaml
name: my_name
channels:
  - conda-forge
dependencies:
  - python=3.7
  - keyring
  - artifacts-keyring
  - pip:
      - AzurePypi_package
```
