### ISSUE TITLE
Package request: scine-chemoton

### ISSUE THREAD

**Issue by awvwgk** [conda-forge/staged-recipes#19515]
### Package name

scine-chemoton

### Package version

2.0.0 (newest)

### Package website

- [ ] scine-chemoton: [`qcscine/chemoton`](https://github.com/qcscine/chemoton) (setuptools, pure Python)
  - [x] scine-database-python: [`qcscine/database`](https://github.com/qcscine/database) (CMake, pybind11, C++)
    - [x] scine-database: [`qcscine/database`](https://github.com/qcscine/database) (CMake, C++)
  - [ ] scine-molassembler-python: [`qcscine/molassembler`](https://github.com/qcscine/molassembler) (CMake, pybind11, C++)
    - [ ] scine-molassembler: [`qcscine/molassembler`](https://github.com/qcscine/molassembler) (CMake, C++)
      - [ ] outcome-cpp: [`ned14/outcome`](https://github.com/ned14/outcome) (CMake, C++)
      - [x] ringdecomposerlib: [`rareylab/RingDecomposerLib`](https://github.com/rareylab/RingDecomposerLib) (CMake, C)

### Package availability

```yaml
source:
  - url: https://github.com/qcscine/chemoton/archive/refs/tags/2.0.0.tar.gz
    sha256: 5016462366c559c41a936a00ff79a05c031eb3f003b699672aec11d1cc394821
  - url: https://github.com/qcscine/development-utils/archive/refs/tags/5.0.0.tar.gz
    sha256: bb2f161ed15811def85ca635924427356564a811779993123077f4ada048be84
    folder: dev
```

```yaml
source:
  - url: https://github.com/qcscine/molassembler/archive/refs/tags/1.2.0.tar.gz
    sha256: a515e2d820b9f1d3e7b07af73707cfd829f6a43761f09396fd368b29d2a93b72
  - url: https://github.com/qcscine/development-utils/archive/refs/tags/5.0.0.tar.gz
    sha256: bb2f161ed15811def85ca635924427356564a811779993123077f4ada048be84
    folder: dev
```

```yaml
source:
  - url: https://github.com/qcscine/database/archive/refs/tags/1.0.0.tar.gz
    sha256: 3e1298efbefb97886575c46fd537d62493f69fe4324667217c096cffa6763e31
  - url: https://github.com/qcscine/development-utils/archive/refs/tags/5.0.0.tar.gz
    sha256: bb2f161ed15811def85ca635924427356564a811779993123077f4ada048be84
    folder: dev
```

```yaml
source:
  url: https://github.com/ned14/outcome/archive/refs/tags/v2.2.3.tar.gz
  sha256: 31cc987d73b2625a70f35083ccff26d1c2634d89304f1ea606a294da36cb2958
```

```yaml
source:
  url: https://github.com/rareylab/RingDecomposerLib/archive/refs/tags/v1.1.3_rdkit.tar.gz
  sha256: 944b5816712a48bbf88aa25d4300ce11871ddf6e971218eac08f90ed2192f715
```

### Additional comments

Template heavy C++ code in the dependency tree (long compilation times, huge libs) best split off Python bindings as separate packages. Tried a couple of the dependencies already

- #19499 
- #19502 
- #19500 
- #19556

### Package is not available

- [X] The package is not available on conda-forge.

### No previous issues or open PRs

- [X] No previous issue exists and no PR has been opened.
