### ISSUE TITLE
Idea: MPI metapackage and features

### ISSUE THREAD

**Issue by tadeu** [conda-forge/staged-recipes#2028]
There are some packages that may depend on MPI or not (e.g., PETSc), and some packages that depend on MPI, but should be different for different MPI versions (`openmpi`, `mpich`, `Microsoft MPI 6.0`, `Microsoft MPI 7.1`, etc.).

My idea is to create a `mpi` metapackage that is similar to the `vc` metapackage: it tracks the current "flavor" of `MPI` that the user "wants" (or none at all).

Here is a very simple example for the `meta.yaml` of such package, but for only a single type, and without using jinja:

```yaml
package:
  name: mpi
  version: "msmpi71"

build:
  track_features:
    - msmpi71
    
about:
  summary: |
      A meta-package to track MPI version of libraries such as mpi4py and PETSc.
      This version should be used with MS MPI v7.1, from here: https://www.microsoft.com/en-us/download/details.aspx?id=52981
```

The version/feature name could be set via environment variable and jinja.

My questions are:

* Do you think this is interesting?
* What is the support that conda-forge gives for building packages with features? (e.g., build `PETSc` without MPI, and with `MS MPI 7.1` on Windows) 

cc @jakirkham @dalcinl @minrk @ocefpaf
