### ISSUE TITLE
`bravado-core` needs `jsonschema[format]` that is `jsondchema-with-format` for conda

### ISSUE THREAD

**Issue by peterbandi** [conda-forge/staged-recipes#22226]
### Bug:

There is a problem with the `bravado-core` package. According to their `setup.py` the package [requires](https://github.com/Yelp/bravado-core/blob/ac5e46d618d4f7720f79eba02edad221a50047e1/setup.py#L14) `jsonschema[format]` so `jsonschema` with the optional `format` extension. Unfortunately, the conda package from conda-forge only lists `jsonschema` as a dependency. Since conda does not support optional dependencies there is a `jsonschema-with-format` package as a replacement.

I am trying to use `neptune-client` with `pytorch-lightning`. The latter checks if all the necessary packages installed with the deprecated (but sill working) `pkg_resources`. That keeps raising exception until all the packages installed from the `jsonschema[format]` pip configuration. With `jsonschema-with-format` installed manually it works.

 `neptune-client` requires `bravado` that requires `bravado-core`.

The following configuration **does not** work:
```yaml
channels:
  - conda-forge
  - defaults
dependencies:
  - neptune-client=1.0.2=pyhd8ed1ab_0
  - pytorch=1.13.1=cuda112py39hb0b7ed5_200
  - pytorch-lightning=1.9.3=pyhd8ed1ab_0
```

In the environment created from the configuration above the following code (copied from pytorch-lightning) reports that `neptune-client` is not available:
```python
from lightning_utilities.core.imports import RequirementCache
_NEPTUNE_AVAILABLE = RequirementCache("neptune-client")
print(f"Neptune-client is available: {bool(_NEPTUNE_AVAILABLE)}")
```

Adding the `jsonschema-with-format` package, the conda equivalent of the pip `jsonschema[format]` fixes the issue above:
```yaml
channels:
  - conda-forge
  - defaults
dependencies:
  - jsonschema-with-format=4.17.3=pyhd8ed1ab_0
  - neptune-client=1.0.2=pyhd8ed1ab_0
  - pytorch=1.13.1=cuda112py39hb0b7ed5_200
  - pytorch-lightning=1.9.3=pyhd8ed1ab_0
```

Now the python code above should report that the `neptune-client` is available.
