### ISSUE TITLE
One package with two versions on pypi (gsconfig)?

### ISSUE THREAD

**Issue by snowman2** [conda-forge/staged-recipes#2996]
Is there a good way to combine one package that has two versions on pypi into a single version on conda-forge?

Python 2: https://pypi.python.org/pypi/gsconfig
Python 3: https://pypi.python.org/pypi/gsconfig-py3

**Comment by snowman2** [comment]
Here is an interesting discussion on history of the two versions:
https://github.com/boundlessgeo/gsconfig/issues/98

**Comment by isuruf** [comment]
You can use selectors for the two urls.
```yaml
source:
  url: https://pypi.io/packages/source/g/gsconfig/gsconfig-{{ version }}.tar.gz           # [py2k]
  url: https://pypi.io/packages/source/g/gsconfig-py3/gsconfig-py3-{{ version }}.tar.gz   # [py3k]
```
