### ISSUE TITLE
Add portaudio

### ISSUE THREAD

**Issue by isuruf** [conda-forge/staged-recipes#3094]
`octave` package is currently using this package from defaults.

**Comment by jakirkham** [comment]
AFAICT the recipe's source isn't available. I suppose we could cobble together our own, but it would nice to avoid accidentally breaking it somehow. @mingwandroid, do you know how we might get access to this recipe?

**Comment by mingwandroid** [comment]
It seems to be an old-style recipe. Here's build.sh:

```
#!/bin/bash

./configure --with-pic --prefix=$PREFIX
make
make install

if [ `uname` == Darwin ]; then
    cp include/pa_mac_core.h $PREFIX/include
fi
```

Here's meta.yaml:

```
source:
  fn: pa_stable_v19_20111121.tgz
  md5: 25c85c1cc5e9e657486cbc299c6c035a

about:
  home: http://www.portaudio.com/
  license: MIT
  license_file: LICENSE.txt
  summary: A cross platform, open-source, audio I/O library
  description: |
    PortAudio is a free, cross-platform, open-source, audio I/O library. It
    lets you write simple audio programs in 'C' or C++ that will compile and run on many platforms including Windows, Macintosh OS X, and Unix
    (OSS/ALSA).
  doc_url: http://www.portaudio.com/docs.html
  dev_url: https://github.com/EddieRingle/portaudio
```
