### ISSUE TITLE
Cache conda packages on AppVeyor 

### ISSUE THREAD

**Issue by jjhelmus** [conda-forge/staged-recipes#610]
It should be possible to cache the conda packages which are always installed on AppVeyor to speed up the build.  AppVeyor provides [documentation](https://www.appveyor.com/docs/build-cache) on using a build cache.

My current plan on how to implements this is to cache all the packages which are downloaded and install by the following lines of the appveyor.yml file

``` yaml
    - cmd: conda update --yes --quiet conda
    - cmd: set PYTHONUNBUFFERED=1
    - cmd: conda config --add channels conda-forge
    - cmd: conda install --yes --quiet obvious-ci conda-build-all
```

These packages come out to ~30 MB for both win-32 and win-64, so ~60 MB total which is under the 100 MB max cache recommendation from AppVeyor.  On though would be to add a file backed channel to the conda configuration and then copy the bz2 files from the Miniconda package cache into this directory after installing conda-build-all.  The packages would still need to be extracted from this directory.

AppVeyor allows cache-invalidation by watching for changes to a specified files in the repository.  Adding two files for invalidating the win-32 and win-64 caches would be prudent.  We could roll a cache number in these files whenever new packages are released which are installed by these commands.  This would require someone to watch for this to occur but it may be possible to automate this process. 

I'll try to put together a example PR on this topic in the coming week.
