### ISSUE TITLE
Unsatisfiable dependance with [py36]

### ISSUE THREAD

**Issue by dgasmith** [conda-forge/staged-recipes#7656]
Pydantic builds are failing during the `run` stage with the following error:
```
Solving environment: ...working... failed
710failed to get install actions, retrying.  exception was: Unsatisfiable dependencies for platform win-64: {'pydantic==0.18.2=py37_2'}
711WARNING:conda_build.build:failed to get install actions, retrying.  exception was: Unsatisfiable dependencies for platform win-64: {'pydantic==0.18.2=py37_2'}
712Tests failed for pydantic-0.18.2-py37_2.tar.bz2 - moving package to C:\bld\broken
713WARNING:conda_build.build:Tests failed for pydantic-0.18.2-py37_2.tar.bz2 - moving package to C:\bld\broken
714TESTS FAILED: pydantic-0.18.2-py37_2.tar.bz2
715
```

Open issue is [here](https://github.com/conda-forge/pydantic-feedstock/pull/4) and relevant bit of build is here:
```
requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - dataclasses >=0.6  # [py36]
```

Everything works cleanly on Python 3.6, but on Python 3.7 it still tries to pull the conda-forge dataclasses module. The dataclasses module is deprecated and removed in Python 3.6 as it is now a Python 3.7 base module.

Any ideas?

**Comment by dgasmith** [comment]
Performed a work around as follows:
```
build:
  number: 2
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv"
  skip: True  # [py2k or py35]

requirements:
  host:
    - python
    - pip
  run:
    - python
    - dataclasses >=0.6  # [py36]
```

Not exactly an elegant solution, but appears to work.
